#!/usr/bin/env python
"""Emit the spec catalogue as JSON for the browser build.

The web checker must apply the same numbers as the CLI. Rather than retyping
resolutions into JavaScript — where they would silently drift the first time a
store changes a rule — the YAML catalogue stays the single source of truth and
this script projects it into ``web/lib/specs.json``.

Run with ``--check`` in CI to fail when the committed JSON is stale.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from launchpilot.core.models.app_metadata import LIMITS
from launchpilot.core.models.report import Store
from launchpilot.core.models.testing import REQUIRED_DAYS, REQUIRED_TESTERS
from launchpilot.core.services.market_scanner import COUNTRY_NAMES, DEFAULT_STOREFRONTS
from launchpilot.core.specs.registry import (
    load_app_health_spec,
    load_aso_spec,
    load_market_spec,
    load_pricing_spec,
    load_spec,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "web" / "lib" / "specs.json"

BANNER = (
    "GENERATED by scripts/export_specs.py from core/specs/*.yaml. "
    "Do not edit by hand; edit the YAML and re-run the script."
)


def build() -> dict[str, object]:
    stores = {}
    for store in Store:
        spec = load_spec(store)
        payload = spec.model_dump(mode="json")
        payload.pop("store", None)
        stores[store.value] = payload

    aso_spec = load_aso_spec()
    aso = aso_spec.model_dump(mode="json")

    # Sets serialise in arbitrary order — Python randomises string hashing per
    # process — so an unsorted set makes this file differ on every run and the
    # CI staleness check fail for no reason.
    #
    # Derived from the model rather than hard-coded: an earlier version listed
    # the set fields by name, and adding `prose_stopwords` without remembering
    # to extend that list is exactly how this broke.
    for name, value in vars(aso_spec).items():
        if isinstance(value, set):
            aso[name] = sorted(value)

    return {
        "_comment": BANNER,
        "stores": stores,
        "aso": aso,
        "market": load_market_spec().model_dump(mode="json"),
        "app_health": load_app_health_spec().model_dump(mode="json"),
        "pricing": load_pricing_spec().model_dump(mode="json"),
        "listing_limits": {
            store.value: {key: limit.model_dump(mode="json") for key, limit in limits.items()}
            for store, limits in LIMITS.items()
        },
        "closed_testing": {
            "required_testers": REQUIRED_TESTERS,
            "required_days": REQUIRED_DAYS,
        },
        "storefronts": {
            "default": list(DEFAULT_STOREFRONTS),
            "names": COUNTRY_NAMES,
        },
    }


def render() -> str:
    return json.dumps(build(), indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed file differs from freshly generated output.",
    )
    args = parser.parse_args()

    generated = render()

    if args.check:
        if not OUTPUT.exists():
            print(f"error: {OUTPUT.relative_to(REPO_ROOT)} is missing", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != generated:
            print(
                f"error: {OUTPUT.relative_to(REPO_ROOT)} is out of date.\n"
                "       Run: uv run python scripts/export_specs.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.relative_to(REPO_ROOT)} is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
