#!/usr/bin/env python
"""Generate tiny real images plus the facts Pillow reads from them.

`web/lib/image-facts.js` reimplements what Pillow reports for a file: its
dimensions, colour mode, and whether it carries an alpha channel. That is the
input every rule depends on, so a parser bug would make the web page disagree
with the CLI even though the rule engines are conformant.

The conformance corpus covers rules-given-facts. This covers facts-given-bytes,
which is the other half. Fixtures are deliberately tiny — a few hundred bytes —
because only the container headers matter.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from PIL import Image, PngImagePlugin

from launchpilot.core.services.image_validator import read_facts

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_DIR = REPO_ROOT / "web" / "test" / "fixtures"
MANIFEST = FIXTURE_DIR / "fixtures.json"


def _write_palette_with_transparency(path: Path) -> None:
    """A palette PNG whose alpha lives in a tRNS chunk, not the colour type.

    The colour-type byte says 3 (palette, no alpha), so a parser that reads only
    that byte would wrongly call this opaque. Both stores reject it.
    """
    img = Image.new("P", (40, 60))
    img.putpalette([0, 0, 0] + [255, 0, 0] * 255)
    img.info["transparency"] = 0
    img.save(path, format="PNG", transparency=0)


def build_fixtures() -> list[dict[str, object]]:
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)

    builders: list[tuple[str, object]] = [
        ("rgb.png", lambda p: Image.new("RGB", (40, 60), "navy").save(p, format="PNG")),
        (
            "rgba.png",
            lambda p: Image.new("RGBA", (40, 60), (10, 20, 30, 128)).save(p, format="PNG"),
        ),
        ("greyscale.png", lambda p: Image.new("L", (40, 60), 128).save(p, format="PNG")),
        (
            "greyscale-alpha.png",
            lambda p: Image.new("LA", (40, 60), (128, 200)).save(p, format="PNG"),
        ),
        ("palette.png", lambda p: Image.new("P", (40, 60)).save(p, format="PNG")),
        ("palette-trns.png", _write_palette_with_transparency),
        ("rgb.jpg", lambda p: Image.new("RGB", (61, 43), "teal").save(p, format="JPEG")),
        ("cmyk.jpg", lambda p: Image.new("CMYK", (33, 77)).save(p, format="JPEG")),
        ("greyscale.jpg", lambda p: Image.new("L", (24, 24), 90).save(p, format="JPEG")),
        # Landscape, and a size that also exercises the two-byte length path.
        ("wide.jpg", lambda p: Image.new("RGB", (300, 120), "orange").save(p, format="JPEG")),
        # PNG carrying metadata chunks before IDAT, so chunk walking is exercised.
        ("rgb-with-text.png", _write_png_with_text),
    ]

    manifest = []
    for name, builder in builders:
        path = FIXTURE_DIR / name
        builder(path)  # type: ignore[operator]
        facts = read_facts(path)
        manifest.append(
            {
                "file": name,
                "width": facts.width,
                "height": facts.height,
                "imageFormat": facts.image_format,
                "mode": facts.mode,
                "hasAlpha": facts.has_alpha,
                "sizeBytes": facts.size_bytes,
            }
        )
    return manifest


def _write_png_with_text(path: Path) -> None:
    meta = PngImagePlugin.PngInfo()
    meta.add_text("Comment", "chunk walking should skip this")
    Image.new("RGB", (48, 24), "purple").save(path, format="PNG", pnginfo=meta)


def render(manifest: list[dict[str, object]]) -> str:
    payload = {
        "_comment": (
            "GENERATED by scripts/export_parser_fixtures.py. Values are what Pillow "
            "reports; web/test/parser.test.js asserts the JS parser agrees."
        ),
        "fixtures": manifest,
    }
    return json.dumps(payload, indent=2) + "\n"


def read_committed() -> list[dict[str, object]]:
    """Re-read the committed fixture images and report what Pillow sees.

    ``--check`` compares against this rather than against freshly encoded images.
    Pillow compresses PNGs through zlib, whose output differs between platforms,
    so re-encoding on Linux produces different bytes — and different file sizes —
    from the macOS run that generated the committed fixtures. Those differences
    are not drift.

    The invariant worth enforcing is narrower and platform-independent: the facts
    recorded in the manifest still describe the files actually committed.
    """
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    out = []
    for entry in manifest["fixtures"]:
        facts = read_facts(FIXTURE_DIR / str(entry["file"]))
        out.append(
            {
                "file": entry["file"],
                "width": facts.width,
                "height": facts.height,
                "imageFormat": facts.image_format,
                "mode": facts.mode,
                "hasAlpha": facts.has_alpha,
                "sizeBytes": facts.size_bytes,
            }
        )
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the manifest still describes the committed fixture images.",
    )
    args = parser.parse_args()

    if args.check:
        if not MANIFEST.exists():
            print("error: fixtures manifest is missing", file=sys.stderr)
            return 1

        expected = json.loads(MANIFEST.read_text(encoding="utf-8"))["fixtures"]
        actual = read_committed()

        if expected != actual:
            print(
                "error: web/test/fixtures/fixtures.json no longer matches the "
                "committed images.\n"
                "       Run: uv run python scripts/export_parser_fixtures.py",
                file=sys.stderr,
            )
            for want, got in zip(expected, actual, strict=True):
                if want != got:
                    print(f"       {want['file']}: {want} != {got}", file=sys.stderr)
            return 1

        print(f"web/test/fixtures is consistent ({len(actual)} images)")
        return 0

    MANIFEST.write_text(render(build_fixtures()), encoding="utf-8")
    print(f"wrote {MANIFEST.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
