/**
 * Conformance: the browser engine must agree with the Python validator.
 *
 * The corpus in conformance-cases.json is generated by running the Python
 * implementation — the one the main pytest suite covers — over a grid of
 * inputs. If these tests fail, the two engines have drifted and users would get
 * different answers from the web page and the CLI for the same file.
 *
 * Run with: node --test web/test/
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { loadSpecs, validateFacts, validateSet } from '../lib/validator.js';
import { loadAso, auditField, buildField, tokenize } from '../lib/keywords.js';

const here = dirname(fileURLToPath(import.meta.url));
const specs = JSON.parse(readFileSync(join(here, '..', 'lib', 'specs.json'), 'utf8'));
const corpus = JSON.parse(readFileSync(join(here, 'conformance-cases.json'), 'utf8'));

loadSpecs(specs);
loadAso(specs);

function describeCase(c) {
  const f = c.facts;
  return `${f.width}x${f.height} ${f.mode}/${f.imageFormat} alpha=${f.hasAlpha} ` +
    `${Math.round(f.sizeBytes / 1024)}KB [${c.stores.join('+')}]`;
}

test('per-file findings match the Python validator', () => {
  const mismatches = [];

  for (const c of corpus.cases) {
    const result = validateFacts(c.facts, c.stores);
    const actual = result.findings.map((f) => f.code).sort();

    if (JSON.stringify(actual) !== JSON.stringify(c.expectedCodes)) {
      mismatches.push(
        `${describeCase(c)}\n    python: ${c.expectedCodes.join(', ') || '(none)'}` +
          `\n    js:     ${actual.join(', ') || '(none)'}`,
      );
    }
  }

  assert.equal(
    mismatches.length,
    0,
    `${mismatches.length}/${corpus.cases.length} cases diverged:\n\n${mismatches.slice(0, 10).join('\n\n')}`,
  );
});

test('per-file status matches the Python validator', () => {
  for (const c of corpus.cases) {
    const result = validateFacts(c.facts, c.stores);
    assert.equal(result.status, c.expectedStatus, describeCase(c));
  }
});

test('detected device class matches the Python validator', () => {
  for (const c of corpus.cases) {
    const result = validateFacts(c.facts, c.stores);
    assert.equal(result.deviceClass, c.expectedDeviceClass, describeCase(c));
  }
});

test('set-level findings match the Python validator', () => {
  for (const c of corpus.setCases) {
    const assets = c.sizes.map((size) =>
      validateFacts(
        {
          width: size.width,
          height: size.height,
          imageFormat: 'PNG',
          mode: 'RGB',
          hasAlpha: false,
          sizeBytes: 512 * 1024,
        },
        c.stores,
      ),
    );
    const actual = validateSet(assets, c.stores)
      .map((f) => f.code)
      .sort();
    assert.deepEqual(actual, c.expectedCodes, c.name);
  }
});

test('the corpus actually exercises every rule the engine can emit', () => {
  // A corpus that silently stopped covering a rule would let that rule drift
  // undetected, so assert breadth rather than trusting the grid.
  const covered = new Set(corpus.cases.flatMap((c) => c.expectedCodes));
  for (const c of corpus.setCases) c.expectedCodes.forEach((code) => covered.add(code));

  const expected = [
    'APPLE_ALPHA_CHANNEL',
    'APPLE_COLOR_SPACE',
    'APPLE_FORMAT',
    'APPLE_LEGACY_SIZE',
    'APPLE_SIZE_DEPRECATED',
    'APPLE_SIZE_UNKNOWN',
    'APPLE_TOO_MANY_PER_CLASS',
    'GOOGLE_ALPHA_CHANNEL',
    'GOOGLE_COLOR_SPACE',
    'GOOGLE_FORMAT',
    'GOOGLE_TOO_FEW',
    'PLAY_ASPECT_RATIO',
    'PLAY_BELOW_RECOMMENDED',
    'PLAY_FILE_TOO_LARGE',
    'PLAY_MAX_TWICE_MIN',
    'PLAY_SIDE_TOO_LARGE',
    'PLAY_SIDE_TOO_SMALL',
    'SET_MIXED_SIZES',
  ];

  const missing = expected.filter((code) => !covered.has(code));
  assert.deepEqual(missing, [], `corpus no longer covers: ${missing.join(', ')}`);
});

// --- keyword field -------------------------------------------------------


test('keyword findings match the Python builder', () => {
  for (const c of corpus.keywordCases) {
    const report = auditField(c.field, {
      title: c.title,
      subtitle: c.subtitle,
      targets: c.targets,
    });
    assert.deepEqual(
      [...report.findings.map((f) => f.code)].sort(),
      c.expectedCodes,
      `${c.name}: finding codes`,
    );
  }
});

test('keyword waste accounting matches the Python builder', () => {
  for (const c of corpus.keywordCases) {
    const report = auditField(c.field, {
      title: c.title,
      subtitle: c.subtitle,
      targets: c.targets,
    });
    assert.equal(report.wastedCharacters, c.expectedWasted, `${c.name}: wasted characters`);
    assert.equal(report.length, c.expectedLength, `${c.name}: length`);
  }
});

test('coverage analysis matches the Python builder', () => {
  for (const c of corpus.keywordCases) {
    const report = auditField(c.field, {
      title: c.title,
      subtitle: c.subtitle,
      targets: c.targets,
    });
    assert.deepEqual(
      report.coverage.map((x) => ({
        phrase: x.phrase,
        covered: x.covered,
        missing: x.missingWords,
      })),
      c.expectedCoverage,
      `${c.name}: coverage`,
    );
    assert.deepEqual(report.uncoveredTargets, c.expectedUncovered, `${c.name}: uncovered`);
  }
});

test('the indexed word pool matches the Python builder', () => {
  for (const c of corpus.keywordCases) {
    const report = auditField(c.field, {
      title: c.title,
      subtitle: c.subtitle,
      targets: c.targets,
    });
    assert.deepEqual(report.indexedWords, c.expectedIndexedWords, `${c.name}: indexed words`);
  }
});

test('suggested rebuilds match the Python builder', () => {
  for (const c of corpus.keywordCases) {
    const report = auditField(c.field, {
      title: c.title,
      subtitle: c.subtitle,
      targets: c.targets,
    });
    assert.equal(report.suggestedField, c.expectedSuggestion, `${c.name}: suggestion`);
  }
});

test('field construction matches the Python builder', () => {
  for (const c of corpus.keywordBuildCases) {
    assert.equal(
      buildField(c.targets, { title: c.title, subtitle: c.subtitle }),
      c.expectedField,
      `${c.name}`,
    );
  }
});

test('tokenisation keeps accented words whole', () => {
  // JavaScript's \w is ASCII-only, so a naive port splits "café" into
  // "caf" + "é" where Python's re.UNICODE keeps it intact.
  assert.deepEqual(tokenize('Café Météo'), ['café', 'météo']);
  assert.deepEqual(tokenize('Kaizen: Habits & Streaks'), ['kaizen', 'habits', 'streaks']);
});

test('the keyword corpus exercises every rule the engine can emit', () => {
  const emitted = new Set(corpus.keywordCases.flatMap((c) => c.expectedCodes));
  for (const code of Object.keys(specs.aso.findings)) {
    if (code === 'ASO_WASTED_BUDGET') continue; // informational, not emitted as a finding
    assert.ok(emitted.has(code), `no conformance case covers ${code}`);
  }
});
